spring:
  application:
    name: calorie-intake-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none  # Options: none, update, create, create-drop, validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

com:
  miczarne:
    jwt:
      secret: ${JWT_SECRET}
